version: '3.7'

services:
    db:
        build:
            context: ./database/
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        restart: always
        expose:
          - 5432
    web:
      environment:
        - DATABASE_URL=postgres://postgres:password@db/postgres
        - DJANGO_MANAGEPY_MIGRATE=on
      env_file:
        - ./backend/.env
      build:
        context: ./backend/
      links:
        - db:db
      ports:
        - 8000:8000

