FROM python:3.8

ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY requirements.txt /code/
RUN apt-get update \
&& apt install libgl1-mesa-glx -y \
&& apt-get install 'libsm6' \
    'libxext6' -y \
&& apt-get install 
RUN pip install -r requirements.txt
COPY . /code/
