# Generated by Django 3.1.5 on 2021-03-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('cam_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cam_name', models.CharField(blank=True, max_length=40, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('cam_status', models.IntegerField(blank=True, null=True)),
                ('cam_ip', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'camera',
                'managed': True,
            },
        ),
    ]
