# Generated by Django 3.1.5 on 2021-03-06 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('movement_id', models.IntegerField(primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(blank=True, null=True)),
                ('person_detected', models.IntegerField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('camera', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='camera.camera')),
            ],
            options={
                'db_table': 'movement',
                'managed': True,
            },
        ),
    ]
